### ISSUE TITLE
Running the pipeline from command line with input options for the nodes

### ISSUE THREAD

**Issue by rakshith95** [michalpolic/hololens_mapper#10]
Hello @michalpolic , 
I'm able to run a pipeline from the command line as: 
` 
./third_party/meshroom/bin/meshroom_compute mapper.mg --cache <cache_path>
`
And this runs fine, with the saved inputs for the nodes, but I was wondering if there is a way to run it by specifying also the input parameters for each node (or just the first node) in the pipeine.

EDIT: One way to do this would probably be just editing the pipeline mg file, but if you know some other way, that would be great

**Comment by rakshith95** [comment]
One way to do this would probably be just editing the pipeline `mg` file, but if you know some other way, that would be great

**Comment by michalpolic** [comment]
Hello @rakshith95. The interface is written such a way that your "meshroom_compute mapper.mg" is a JSON that specifies the inputs to all the nodes. The easiest way is to modify the configuration in "meshroom_compute mapper.mg".

**Comment by rakshith95** [comment]
Okay, thank you. I thought if there was some other way to feed in the inputs it would be more convenient than editing the 'mg' file, but I will stick with this then.
