### ISSUE TITLE
Camera Parameters inputs for HlocQueryComposer

### ISSUE THREAD

**Issue by rakshith95** [michalpolic/hololens_mapper#7]
Hello, 
For the HlocQueryComposer node, there is are inputs for Camera Parameters with the following fields: 
Camera model:
Width:
Height:
Parameters:

While width, and height are clear enough, I'm not sure what to enter for the Camera model, and parameters.   Could you please let me know in what format the Camera model, and parameters columns should be filled? 
 
 Thank you!

**Comment by michalpolic** [comment]
Yes, sure. Thank you for the question. The HLOC is using the COLMAP camera format, i.e., the model names and related parameters can be find in https://github.com/colmap/colmap/blob/dev/src/base/camera_models.h . There is documentation for each camera model and the order of required parameters.
